# Default configurations for different model types

linear_regression:
  fit_intercept: true
  copy_X: true
  n_jobs: -1

lightgbm:
  objective: regression
  metric: rmse
  boosting_type: gbdt
  num_leaves: 31
  learning_rate: 0.05
  feature_fraction: 0.9
  bagging_fraction: 0.8
  bagging_freq: 5
  verbose: -1
  random_state: 42
  num_boost_round: 100
  early_stopping_rounds: 10

random_forest:
  n_estimators: 100
  max_depth: null
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: sqrt
  bootstrap: true
  random_state: 42
  n_jobs: -1
