# Default training configurations

default:
  test_size: 0.2
  random_state: 42
  scale_features: true
  handle_missing: true
  missing_strategy: mean

sample_dataset:
  n_samples: 1000
  n_features: 10
  noise: 10

wandb:
  project: ml-training-pipeline
  tags:
    - training
    - experiment

huggingface:
  private_repo: false
  upload_enabled: false
